runtime: java
env: flex
runtime_config:
  jdk: openjdk8
env_variables:
  SPRING_PROFILES_ACTIVE: "gcp,mysql"

manual_scaling: 
  instances: 1
entrypoint: java -noverify -jar target/TestHibernate-0.1.jar
